### ISSUE TITLE
Making the site Mobile friendly

### ISSUE THREAD

**Issue by sahitpj** [pydatagn/pydatagn.github.io#4]

**Comment by emorraa** [comment]
I'll probably work on this tonight, can you please just tell me what kind of mobile-friendly-site type you want?

**Comment by jakewhoward** [comment]
I can handle this.

**Comment by sahitpj** [comment]
hey @emorraa I think the main page, picture is causing it to be like that. Just check that out.

**Comment by palmerhinchliffe** [comment]
I'll have a go at this

**Comment by sahitpj** [comment]
please make sure to not overlap your PRs

**Comment by praveen-me** [comment]
Can I work on it?

**Comment by jakewhoward** [comment]
@sahitpj I can get this done in about 20 minutes.  I just dont want to work on it if someone else is assigned to it.

**Comment by sahitpj** [comment]
@jakewhoward yeah please do, I don't think anyone is currently

**Comment by jakewhoward** [comment]
@sahitpj on it, Ill send you a PR later today.  Thanks!
